disabled_rules: # rule identifiers to exclude from running
  - variable_name
  - force_cast
  - todo
  - file_length
  - weak_delegate
  - type_name
  - large_tuple
opt_in_rules: # some rules are only opt-in
  - empty_count
  # - missing_docs # Broken in swiftlint 0.12.0 with XCode 8
  # Find all the available rules by running:
  # swiftlint rules
excluded:
  - Carthage
  - Example
  - Tests

  
line_length: 120
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names